# Generated by Django 4.0.4 on 2022-08-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.IntegerField(default=0)),
                ('pub_date', models.IntegerField(default=0)),
            ],
        ),
    ]
