# Generated by Django 4.0.4 on 2022-08-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detectTrash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='pub_date',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='locations',
            name='question_text',
            field=models.FloatField(default=0),
        ),
    ]
