# Generated by Django 4.0.4 on 2022-08-27 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detectTrash', '0003_rename_pub_date_locations_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locations',
            old_name='longititude',
            new_name='longitude',
        ),
    ]
